[package]
name = "litecluster"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.31.0", features = ["full"] }
tokio-util = "0.7.7"
rusqlite = { version = "0.29.0", features = ["bundled"] }
object_store = "0.8.0"
anyhow = "1.0.44"
async-channel = "1.9"
fallible-iterator = "0.3.0"
tempfile = "3.7.1"
num_cpus = "1.16.0"
uuid = { version = "1.4.1", features = ["v7"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.26"
futures = "0.3.17"
tracing = "0.1"
parking_lot = "0.12.1"
bytes = "1.1.0"
pin-project-lite = "0.2.14"

[dev-dependencies]
rand = "0.8.5"
clap = { version = "4.3.21", features = ["derive"] }
tracing-subscriber = { version = "0.3", features = ["ansi"] }